# Generated by Django 4.1.6 on 2023-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(default='', max_length=70)),
                ('companyname', models.CharField(default='', max_length=70)),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
