# Generated by Django 4.1.6 on 2023-03-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0002_subcategory_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField(default='')),
                ('subcategoryid', models.IntegerField(default='')),
                ('modelyear', models.IntegerField(default='')),
                ('variant', models.CharField(default='', max_length=70)),
                ('price', models.IntegerField(default='')),
                ('insured', models.CharField(default='', max_length=70)),
                ('registrationno', models.IntegerField(default='')),
                ('ownername', models.CharField(default='', max_length=70)),
                ('mobileno', models.IntegerField(default='')),
                ('color', models.CharField(default='', max_length=70)),
                ('fueltype', models.CharField(default='', max_length=70)),
                ('noofseats', models.IntegerField(default='')),
                ('transmissiontype', models.CharField(default='', max_length=70)),
                ('picture', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='categoryid',
            field=models.IntegerField(default=''),
        ),
    ]
