# Generated by Django 4.1.6 on 2023-03-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0003_vehicles_alter_subcategory_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='registrationno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
