# Generated by Django 4.1.6 on 2023-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_alter_vehicles_registrationno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categoryid',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='categoryid',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='subcategoryid',
            field=models.CharField(default='', max_length=70),
        ),
    ]
