# Generated by Django 4.1.6 on 2023-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0006_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='mobileno',
            field=models.CharField(default='', max_length=70),
        ),
    ]
